language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- pypy
install:
- pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt --allow-external argparse
- pip install coveralls
- pip install coverage
script:
- PYTHONPATH=. coverage run -m nose2.__main__ -v
after_success:
- coveralls
deploy:
  provider: pypi
  user: jpellerin
  password:
    secure: B4Tc+q8fwYaqr971bDUPSP03AUKev9Jl0/KSWVlSV8zpizBNllZ+wo5YmOqrInDFCbbAm36Y4HyjqBfF/TK2SpmKGmFHbjMFEFXGeYj/ESs7iCKPczgbUL+1d3HgreMr+CbngXcTLv9WNHtAXpXbzfbgeB0QCIy6bSe1K0e9VZ4=
  on:
    tags: true
    all_branches: true
